# ETAPA 1: Construcción (Compilación del JAR)
FROM maven:3.9.6-eclipse-temurin-21-jammy AS build
WORKDIR /app

# Copiar archivos de configuración de Maven
COPY pom.xml .
COPY src ./src

# Compilar el proyecto saltándose los tests para ahorrar tiempo
RUN mvn clean package -DskipTests

# ETAPA 2: Ejecución (Contenedor ligero final)
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Copiar el archivo .jar generado en la Etapa 1 (Con el nombre de estudiantes)
COPY --from=build /app/target/micro_evento-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto oficial asignado a este microservicio
EXPOSE 5010

# Comando definitivo para arrancar la aplicación nativa en nube
ENTRYPOINT ["java", "-jar", "app.jar"]